apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudreve.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudreve.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.cloudreve.system.listen }}
      targetPort: http
      protocol: TCP
      name: http
    - name: aria2-tcp
      targetPort: aria2-tcp
      containerPort: 6888
      protocol: TCP
    - name: aria2-udp
      targetPort: aria2-udp
      containerPort: 6888
      protocol: UDP
  selector:
    {{- include "cloudreve.selectorLabels" . | nindent 4 }}
